version: 2.1
orbs:
  heroku: circleci/heroku@2.0
jobs:
  testing:
    docker:
      - image: cimg/node:lts
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install Angular CLI
          command: npm install -g @angular/cli
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the application
          command: ng build
      - save_cache:
          key: v1-dist-{{ checksum "package.json" }}
          paths:
            - dist
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - restore_cache:
          keys:
            - v1-dist-{{ checksum "package.json" }}
            - v1-dist-
      - run:
          name: Add static.json
          command: |
            echo '{ "root": "dist/", "routes": { "/**": "index.html" } }' > dist/static.json'
      - run:
          name: Add Heroku remote
          command: heroku git:remote -a $HEROKU_APP_NAME
      - run:
          name: Deploy to Heroku
          command: git subtree push --prefix dist heroku master
      - run:
          name: Check deployment status
          command: |
            heroku ps --app $HEROKU_APP_NAME
workflows:
  heroku_deploy:
    jobs:
      - testing
      - deploy:
          requires:
            - testing
